logging:
  level:
    org: ERROR

spring:
  rabbitmq:
    host: swan.rmq.cloudamqp.com
    password: ImStIfzlSEiGk72iJIg1sRphhg6IoMrZ
    username: rbrilnwu
    virtual-host: rbrilnwu
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/./database;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
  jpa:
    hibernate:
      ddl-auto: update